export const DATA = [
    {
        id:'1',
        firstname:'Erkki',
        lastname:'Esimerkki'
    },
    {
        id:'2',
        firstname:'Jouni',
        lastname:'Juntunen'
    },
    {
        id:'3',
        firstname:'Maija',
        lastname:'Meikäläinen'
    },
    {
        id:'4',
        firstname:'Tauno',
        lastname:'Taliaivo'
    },
    {
        id:'5',
        firstname:'Matti',
        lastname: 'Nykänen'
    },
    {
        id:'6',
        firstname:'Saara',
        lastname:'Saaranen'
    },
    {
        id:'7',
        firstname:'Pertti',
        lastname:'Periaate'
    },
    {
        id:'8',
        firstname:'Antti',
        lastname:'Alatalo'
    },
    {
        id:'9',
        firstname:'Bob',
        lastname:'Robertson'
    },
    {
        id:'10',
        firstname:'John',
        lastname:'Smith'
    },
    {
        id:'11',
        firstname:'Ville',
        lastname:'Vallaton'
    },
    {
        id:'12',
        firstname:'Peppi',
        lastname:'Pitkätossu'
    },
    {
        id:'13',
        firstname:'Aku',
        lastname:'Ankka'
    },
    {
        id:'14',
        firstname:'Bart',
        lastname:'Simpson'
    },
    {
        id:'15',
        firstname:'Peter',
        lastname:'Peterson'
    }
]